INSERT INTO public.nutrient (id, name, unit_name) VALUES (2047, 'Energy (Atwater General Factors)', 'KCAL');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2048, 'Energy (Atwater Specific Factors)', 'KCAL');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1001, 'Solids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1002, 'Nitrogen', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1003, 'Protein', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1004, 'Total lipid (fat)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1005, 'Carbohydrate, by difference', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1006, 'Fiber, crude (DO NOT USE - Archived)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1007, 'Ash', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1008, 'Energy', 'KCAL');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1009, 'Starch', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1010, 'Sucrose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1011, 'Glucose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1012, 'Fructose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1013, 'Lactose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1014, 'Maltose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1015, 'Amylose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1016, 'Amylopectin', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1017, 'Pectin', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1018, 'Alcohol, ethyl', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1019, 'Pentosan', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1020, 'Pentoses', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1021, 'Hemicellulose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1022, 'Cellulose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1023, 'pH', 'PH');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1024, 'Specific Gravity', 'SP_GR');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1025, 'Organic acids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1026, 'Acetic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1027, 'Aconitic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1028, 'Benzoic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1029, 'Chelidonic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1030, 'Chlorogenic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1031, 'Cinnamic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1032, 'Citric acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1033, 'Fumaric acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1034, 'Galacturonic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1035, 'Gallic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1036, 'Glycolic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1037, 'Isocitric acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1038, 'Lactic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1039, 'Malic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1040, 'Oxaloacetic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1041, 'Oxalic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1042, 'Phytic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1043, 'Pyruvic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1044, 'Quinic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1045, 'Salicylic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1046, 'Succinic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1047, 'Tartaric acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1048, 'Ursolic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1049, 'Solids, non-fat', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1050, 'Carbohydrate, by summation', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1051, 'Water', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1052, 'Adjusted Nitrogen', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1053, 'Adjusted Protein', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1054, 'Piperine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1055, 'Mannitol', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1056, 'Sorbitol', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1057, 'Caffeine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1058, 'Theobromine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1059, 'Nitrates', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1060, 'Nitrites', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1061, 'Nitrosamine,total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1062, 'Energy', 'kJ');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1063, 'Sugars, Total NLEA', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1064, 'Solids, soluble', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1065, 'Glycogen', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1066, 'Fiber, neutral detergent (DO NOT USE - Archived)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1067, 'Reducing sugars', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1068, 'Beta-glucans', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1069, 'Oligosaccharides', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1070, 'Nonstarch polysaccharides', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1071, 'Resistant starch', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1072, 'Carbohydrate, other', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1073, 'Arabinose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1074, 'Xylose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1075, 'Galactose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1076, 'Raffinose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1077, 'Stachyose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1078, 'Xylitol', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1079, 'Fiber, total dietary', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1080, 'Lignin', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1081, 'Ribose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1082, 'Fiber, soluble', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1083, 'Theophylline', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1084, 'Fiber, insoluble', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1085, 'Total fat (NLEA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1086, 'Total sugar alcohols', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1087, 'Calcium, Ca', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1088, 'Chlorine, Cl', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1089, 'Iron, Fe', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1090, 'Magnesium, Mg', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1091, 'Phosphorus, P', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1092, 'Potassium, K', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1093, 'Sodium, Na', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1094, 'Sulfur, S', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1095, 'Zinc, Zn', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1096, 'Chromium, Cr', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1097, 'Cobalt, Co', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1098, 'Copper, Cu', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1099, 'Fluoride, F', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1100, 'Iodine, I', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1101, 'Manganese, Mn', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1102, 'Molybdenum, Mo', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1103, 'Selenium, Se', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1104, 'Vitamin A, IU', 'IU');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1105, 'Retinol', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1106, 'Vitamin A, RAE', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1107, 'Carotene, beta', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1108, 'Carotene, alpha', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1109, 'Vitamin E (alpha-tocopherol)', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1110, 'Vitamin D (D2 + D3), International Units', 'IU');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1111, 'Vitamin D2 (ergocalciferol)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1112, 'Vitamin D3 (cholecalciferol)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1113, '25-hydroxycholecalciferol', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1114, 'Vitamin D (D2 + D3)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1115, '25-hydroxyergocalciferol', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1116, 'Phytoene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1117, 'Phytofluene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1118, 'Carotene, gamma', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1119, 'Zeaxanthin', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1120, 'Cryptoxanthin, beta', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1121, 'Lutein', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1122, 'Lycopene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1123, 'Lutein + zeaxanthin', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1124, 'Vitamin E (label entry primarily)', 'IU');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1125, 'Tocopherol, beta', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1126, 'Tocopherol, gamma', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1127, 'Tocopherol, delta', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1128, 'Tocotrienol, alpha', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1129, 'Tocotrienol, beta', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1130, 'Tocotrienol, gamma', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1131, 'Tocotrienol, delta', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1132, 'Aluminum, Al', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1133, 'Antimony, Sb', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1134, 'Arsenic, As', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1135, 'Barium, Ba', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1136, 'Beryllium, Be', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1137, 'Boron, B', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1138, 'Bromine, Br', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1139, 'Cadmium, Cd', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1140, 'Gold, Au', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1141, 'Iron, heme', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1142, 'Iron, non-heme', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1143, 'Lead, Pb', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1144, 'Lithium, Li', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1145, 'Mercury, Hg', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1146, 'Nickel, Ni', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1147, 'Rubidium, Rb', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1148, 'Fluoride - DO NOT USE; use 313', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1149, 'Salt, NaCl', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1150, 'Silicon, Si', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1151, 'Silver, Ag', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1152, 'Strontium, Sr', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1153, 'Tin, Sn', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1154, 'Titanium, Ti', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1155, 'Vanadium, V', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1156, 'Vitamin A, RE', 'MCG_RE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1157, 'Carotene', 'MCG_RE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1158, 'Vitamin E', 'MG_ATE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1159, 'cis-beta-Carotene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1160, 'cis-Lycopene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1161, 'cis-Lutein/Zeaxanthin', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1162, 'Vitamin C, total ascorbic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1163, 'Vitamin C, reduced ascorbic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1164, 'Vitamin C, dehydro ascorbic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1165, 'Thiamin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1166, 'Riboflavin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1167, 'Niacin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1168, 'Niacin from tryptophan, determined', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1169, 'Niacin equivalent N406 +N407', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1170, 'Pantothenic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1171, 'Vitamin B-6, pyridoxine, alcohol form', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1172, 'Vitamin B-6, pyridoxal, aldehyde form', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1173, 'Vitamin B-6, pyridoxamine, amine form', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1174, 'Vitamin B-6, N411 + N412 +N413', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1175, 'Vitamin B-6', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1176, 'Biotin', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1177, 'Folate, total', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1178, 'Vitamin B-12', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1179, 'Folate, free', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1180, 'Choline, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1181, 'Inositol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1182, 'Inositol phosphate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1183, 'Vitamin K (Menaquinone-4)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1184, 'Vitamin K (Dihydrophylloquinone)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1185, 'Vitamin K (phylloquinone)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1186, 'Folic acid', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1187, 'Folate, food', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1188, '5-methyl tetrahydrofolate (5-MTHF)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1189, 'Folate, not 5-MTHF', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1190, 'Folate, DFE', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1191, '10-Formyl folic acid (10HCOFA)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1192, '5-Formyltetrahydrofolic acid (5-HCOH4', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1193, 'Tetrahydrofolic acid (THF)', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1194, 'Choline, free', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1195, 'Choline, from phosphocholine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1196, 'Choline, from phosphotidyl choline', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1197, 'Choline, from glycerophosphocholine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1198, 'Betaine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1199, 'Choline, from sphingomyelin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1200, 'p-Hydroxy benzoic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1201, 'Caffeic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1202, 'p-Coumaric acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1203, 'Ellagic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1204, 'Ferrulic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1205, 'Gentisic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1206, 'Tyrosol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1207, 'Vanillic acid', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1208, 'Phenolic acids, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1209, 'Polyphenols, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1210, 'Tryptophan', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1211, 'Threonine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1212, 'Isoleucine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1213, 'Leucine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1214, 'Lysine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1215, 'Methionine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1216, 'Cystine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1217, 'Phenylalanine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1218, 'Tyrosine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1219, 'Valine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1220, 'Arginine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1221, 'Histidine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1222, 'Alanine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1223, 'Aspartic acid', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1224, 'Glutamic acid', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1225, 'Glycine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1226, 'Proline', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1227, 'Serine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1228, 'Hydroxyproline', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1229, 'Cysteine and methionine(sulfer containig AA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1230, 'Phenylalanine and tyrosine (aromatic  AA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1231, 'Asparagine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1232, 'Cysteine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1233, 'Glutamine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1234, 'Taurine', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1235, 'Sugars, added', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1236, 'Sugars, intrinsic', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1237, 'Calcium, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1238, 'Iron, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1239, 'Calcium, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1240, 'Iron, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1241, 'Vitamin C, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1242, 'Vitamin E, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1243, 'Thiamin, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1244, 'Riboflavin, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1245, 'Niacin, added', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1246, 'Vitamin B-12, added', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1247, 'Vitamin C, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1248, 'Vitamin E, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1249, 'Thiamin, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1250, 'Riboflavin, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1251, 'Niacin, intrinsic', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1252, 'Vitamin B-12, intrinsic', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1253, 'Cholesterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1254, 'Glycerides', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1255, 'Phospholipids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1256, 'Glycolipids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1257, 'Fatty acids, total trans', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1258, 'Fatty acids, total saturated', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1259, 'SFA 4:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1260, 'SFA 6:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1261, 'SFA 8:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1262, 'SFA 10:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1263, 'SFA 12:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1264, 'SFA 14:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1265, 'SFA 16:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1266, 'SFA 18:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1267, 'SFA 20:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1268, 'MUFA 18:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1269, 'PUFA 18:2', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1270, 'PUFA 18:3', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1271, 'PUFA 20:4', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1272, 'PUFA 22:6 n-3 (DHA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1273, 'SFA 22:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1274, 'MUFA 14:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1275, 'MUFA 16:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1276, 'PUFA 18:4', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1277, 'MUFA 20:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1278, 'PUFA 20:5 n-3 (EPA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1279, 'MUFA 22:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1280, 'PUFA 22:5 n-3 (DPA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1281, 'TFA 14:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1283, 'Phytosterols', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1284, 'Ergosterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1285, 'Stigmasterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1286, 'Campesterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1287, 'Brassicasterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1288, 'Beta-sitosterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1289, 'Campestanol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1290, 'Unsaponifiable matter (lipids)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1291, 'Fatty acids, other than 607-615, 617-621, 624-632, 652-654, 686-689)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1292, 'Fatty acids, total monounsaturated', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1293, 'Fatty acids, total polyunsaturated', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1294, 'Beta-sitostanol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1295, 'Delta-7-avenasterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1296, 'Delta-5-avenasterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1297, 'Alpha-spinasterol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1298, 'Phytosterols, other', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1299, 'SFA 15:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1300, 'SFA 17:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1301, 'SFA 24:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1302, 'Wax Esters(Total Wax)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1303, 'TFA 16:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1304, 'TFA 18:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1305, 'TFA 22:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1306, 'TFA 18:2 t not further defined', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1307, 'PUFA 18:2 i', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1308, 'PUFA 18:2 t,c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1309, 'PUFA 18:2 c,t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1310, 'TFA 18:2 t,t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1311, 'PUFA 18:2 CLAs', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1312, 'MUFA 24:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1313, 'PUFA 20:2 n-6 c,c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1314, 'MUFA 16:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1315, 'MUFA 18:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1316, 'PUFA 18:2 n-6 c,c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1317, 'MUFA 22:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1318, 'Fatty acids, saturated, other', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1319, 'Fatty acids, monounsat., other', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1320, 'Fatty acids, polyunsat., other', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1321, 'PUFA 18:3 n-6 c,c,c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1322, 'SFA 19:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1323, 'MUFA 17:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1324, 'PUFA 16:2', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1325, 'PUFA 20:3', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1326, 'Fatty acids, total sat., NLEA', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1327, 'Fatty acids, total monounsat., NLEA', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1328, 'Fatty acids, total polyunsat., NLEA', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1329, 'Fatty acids, total trans-monoenoic', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1330, 'Fatty acids, total trans-dienoic', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1331, 'Fatty acids, total trans-polyenoic', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1332, 'SFA 13:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1333, 'MUFA 15:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1334, 'PUFA 22:2', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1335, 'SFA 11:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1336, 'ORAC, Hydrophyllic', 'UMOL_TE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1337, 'ORAC, Lipophillic', 'UMOL_TE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1338, 'ORAC, Total', 'UMOL_TE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1339, 'Total Phenolics', 'MG_GAE');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1340, 'Daidzein', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1341, 'Genistein', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1342, 'Glycitein', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1343, 'Isoflavones', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1344, 'Biochanin A', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1345, 'Formononetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1346, 'Coumestrol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1347, 'Flavonoids, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1348, 'Anthocyanidins', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1349, 'Cyanidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1350, 'Proanthocyanidin (dimer-A linkage)', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1351, 'Proanthocyanidin monomers', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1352, 'Proanthocyanidin dimers', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1353, 'Proanthocyanidin trimers', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1354, 'Proanthocyanidin 4-6mers', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1355, 'Proanthocyanidin 7-10mers', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1356, 'Proanthocyanidin polymers (>10mers)', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1357, 'Delphinidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1358, 'Malvidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1359, 'Pelargonidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1360, 'Peonidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1361, 'Petunidin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1362, 'Flavans, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1363, 'Catechins, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1364, 'Catechin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1365, 'Epigallocatechin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1366, 'Epicatechin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1367, 'Epicatechin-3-gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1368, 'Epigallocatechin-3-gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1369, 'Procyanidins, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1370, 'Theaflavins', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1371, 'Thearubigins', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1372, 'Flavanones, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1373, 'Eriodictyol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1374, 'Hesperetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1375, 'Isosakuranetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1376, 'Liquiritigenin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1377, 'Naringenin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1378, 'Flavones, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1379, 'Apigenin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1380, 'Chrysoeriol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1381, 'Diosmetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1382, 'Luteolin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1383, 'Nobiletin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1384, 'Sinensetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1385, 'Tangeretin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1386, 'Flavonols, total', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1387, 'Isorhamnetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1388, 'Kaempferol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1389, 'Limocitrin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1390, 'Myricetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1391, 'Quercetin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1392, 'Theogallin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1393, 'Theaflavin -3,3'' -digallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1394, 'Theaflavin -3'' -gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1395, 'Theaflavin -3 -gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1396, '(+) -Gallo catechin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1397, '(+)-Catechin 3-gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1398, '(+)-Gallocatechin 3-gallate', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1399, 'Mannose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1400, 'Triose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1401, 'Tetrose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1402, 'Other Saccharides', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1403, 'Inulin', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1404, 'PUFA 18:3 n-3 c,c,c (ALA)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1405, 'PUFA 20:3 n-3', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1406, 'PUFA 20:4 n-6', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1407, 'PUFA 20:4 n-3', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1408, 'PUFA 2:4 n-6', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1409, 'PUFA 18:3i', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1410, 'PUFA 21:5', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1411, 'PUFA 22:4', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1412, 'MUFA 18:1-11 t (18:1t n-7)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1413, 'MUFA 18:1-11 c (18:1c n-7)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (1414, 'PUFA 20:3 n-9', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2000, 'Sugars, total including NLEA', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2003, 'SFA 5:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2004, 'SFA 7:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2005, 'SFA 9:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2006, 'SFA 21:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2007, 'SFA 23:0', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2008, 'MUFA 12:1', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2009, 'MUFA 14:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2010, 'MUFA 17:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2011, 'TFA 17:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2012, 'MUFA 20:1 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2013, 'TFA 20:1 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2014, 'MUFA 22:1 n-9', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2015, 'MUFA 22:1 n-11', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2016, 'PUFA 18:2 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2017, 'TFA 18:2 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2018, 'PUFA 18:3 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2019, 'TFA 18:3 t', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2020, 'PUFA 20:3 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2021, 'PUFA 22:3', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2022, 'PUFA 20:4c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2023, 'PUFA 20:5c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2024, 'PUFA 22:5 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2025, 'PUFA 22:6 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2026, 'PUFA 20:2 c', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2027, 'Proximate', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2028, 'trans-beta-Carotene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2029, 'trans-Lycopene', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2032, 'Cryptoxanthin, alpha', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2033, 'Total dietary fiber (AOAC 2011.25)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2034, 'Insoluble dietary fiber (IDF)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2035, 'Soluble dietary fiber (SDFP+SDFS)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2036, 'Soluble dietary fiber (SDFP)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2037, 'Soluble dietary fiber (SDFS)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2038, 'High Molecular Weight Dietary Fiber (HMWDF)', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2039, 'Carbohydrates', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2040, 'Other carotenoids', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2041, 'Tocopherols and tocotrienols', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2042, 'Amino acids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2043, 'Minerals', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2044, 'Lipids', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2045, 'Proximates', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2046, 'Vitamins and Other Components', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2055, 'Total Tocopherols', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2054, 'Total Tocotrienols', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2053, 'Stigmastadiene', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2052, 'Delta-7-Stigmastenol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2049, 'Daidzin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2050, 'Genistin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2051, 'Glycitin', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2057, 'Ergothioneine', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2058, 'Beta-glucan', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2059, 'Vitamin D4', 'UG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2060, 'Ergosta-7-enol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2061, ' Ergosta-7,22-dienol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2062, ' Ergosta-5,7-dienol', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2063, 'Verbascose', 'G');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2064, 'Oligiosaccharides', 'MG');
INSERT INTO public.nutrient (id, name, unit_name) VALUES (2065, 'Low Molecular Weight Dietary Fiber (LMWDF)', 'G');
